#!/bin/bash
input_folder=$1
output_folder=$2
input_format=$3
output_format=$4 
if [ "$input_format" == "dat" ] && [ "$output_format" == "txt" ]; then
    program=./reference-outputs-generators/solver-dat2txt.sh
fi
if [ "$input_format" == "txt" ] && [ "$output_format" == "txt" ]; then
    program=./reference-outputs-generators/solver-txt2txt.sh
fi
   
echo "The output generation dispatcher center (makeOutputs.sh) has been put in charge to produce the reference outputs for the inputs in the folder $input_folder"
echo "The output files will be placed in the folder: $output_folder"
echo "The output files will be generated by the program: $program"
rm -rf $output_folder
mkdir $output_folder
for f in ${input_folder}/*_?.${input_format} ${input_folder}/*_??.${input_format} ${input_folder}/*_???.${input_format}
do
   i=$(echo $f | sed 's/^[^0-9]*\([0-9]*\).*$/\1/' )
   if [[ !  -z  $i  ]]; then
       echo "This generation is done by the program: ${program}"
       echo "Generating file ${output_folder}/output_$i.${output_format} from file ${input_folder}/input_$i.${input_format}"
       echo "$program $f > ${output_folder}/output_$i.${output_format}"
       $program $f > ${output_folder}/output_$i.${output_format}
   fi
done
